version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: kuman-postgres
    environment:
      POSTGRES_DB: kuman
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kuman"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: kuman-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kuman
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres-data: